### PR TITLE
Add tweetProjectOfTheDay

### PR DESCRIPTION
**Pull request by spences10**

### CODE REVIEW

**Comment by spences10** [comment]
Will, add more project ideas as needed, maybe FSS links, not sure how much of the char limit will be used for this, maybe add another function for that before posting??

**Comment by amandeepmittal** [comment]
@spences10 This PR has some conflicts with the version of `bot.js` you have implemented the new snippet of code. Can you please do the same using the latest `bot.js` file?

**Comment by spences10** [comment]
Ok, I'll take the master branch and re-apply my changes, yes? If so close this PR

Thanks :+1: :nerd_face:

**Comment by spences10** [comment]
When trying to run the latest version in my c9 IDE I get the following error:

image

I thought it was because I needed to add the `"use strict"; // added for use on c9` but still doesn't seem to want to work for me, any Ideas @amandeepmittal

**Pull request closed without merging**
