### PR TITLE
Removes redundant config files and check for one hashtag

### PR DESCRIPTION
**Pull request by amandeepmittal**
### Change proposed in this pull request:
  - Remove redundant config files and dependencies

  - Check for only one hashtag
---
###### Thanks to [@miljan-fsd] from [parcel-react-app] for the template 👌

[@miljan-fsd]: https://github.com/miljan-fsd
[parcel-react-app]: https://github.com/miljan-fsd/parcel-react-app

### CODE REVIEW

**Comment by amandeepmittal** [comment]
@raisedadead can you please review the PR. Also, do you want me to include the Twitter API keys in the PR? Currently, it doesn't. Before deploying, you will need those keys.

**Comment by raisedadead** [comment]
Hi @amandeepmittal 

Thanks for these changes. I will get back to you with a review as soon as I am able. Thanks for your patience :)

>  do you want me to include the Twitter API keys in the PR?

This repository is public, we certainly do not want any keys in public.

**Comment by amandeepmittal** [comment]
@raisedadead, apologies for pinging you again but if you get time in coming days/weeks, please have a look at this PR 🙏 And thanks a lot once again, it is always a pleasure to work with you and freeCodeCamp team on this 😄

**Comment by raisedadead** [comment]
Hi @amandeepmittal 

Sorry about the delayed response on this. This PR is not forgotten, it's just that we haven't gotten around to looking at the codebase and how it's all set up on Heroku yet.

But the good news is @zairahira from our staff team will be overseeing this.

In the interest of time would it be possible for you to get on a quick 15-minute call sometime this week, and give us a basic walkthru?

If yes, let me know I will DM you on Twitter.

**Comment by amandeepmittal** [comment]
Thank you @raisedadead! Quincy introduced us on Twitter and I am in touch with Zaira! Will take it forward from there.

**Comment by raisedadead** [comment]
I am going to go ahead and merge this. @zairahira once this is merged I will add some setup files for GitPod for easier development setup. @amandeepmittal we would appreciate some help with understanding how this is deployed.

**Comment by amandeepmittal** [comment]
@raisedadead, it is deployed manually by logging into Heroku console from CLI and then run the command. You can change deployment process in whatever way you think is appropriate. I am pretty sure things have changed for the better with Heroku nowadays.

**Comment by amandeepmittal** [comment]
The only thing to take notice of when deploying a nodejs script on Heroku is to have `Procfile` at the root of the project with the following value:

```shell
worker: node index.js
```

And then in heroku project dashboard, enable worker. I don't where that setting might live nowadays, since I can't login into any of m personal heroku account (I tried contacting their support but still awaiting a resolution).

**Comment by raisedadead** [comment]
Hi @amandeepmittal 

Yeah - I linked the GitHub repo to Heroku and we added the keys to the environment variables, So I think the deployments are now automated.

Now, I am not sure if the issue of spam retweets needs additional code changes because we are still seeing the bot retweeting unwanted tweets.

**Pull request merged**
