### PR TITLE
add travis config

### PR DESCRIPTION
**Pull request by amandeepmittal**
Fixes #

### Change proposed in this pull request:
  - add config for travis

  -
  
  -

---
###### Thanks to [@miljan-fsd] from [parcel-react-app] for the template 👌

[@miljan-fsd]: https://github.com/miljan-fsd
[parcel-react-app]: https://github.com/miljan-fsd/parcel-react-app

### CODE REVIEW

**Comment by amandeepmittal** [comment]
@QuincyLarson I have submitted the request to @freeCodeCamp to access grant to this repo to integrate Travic CI. Please gran the request.

**Comment by QuincyLarson** [comment]
@amandeepmittal @spences10 both of you have admin level access to this repo - the highest level of permission. 

collaborators

And it looks like Travis is ready to go, too:

freecodecamp_100daysofcode-twitter-bot_-_travis_ci

**Comment by spences10** [comment]
I think @amandeepmittal needs to have the org approve access to the repo from Travis, right Aman?

I'll be honest I haven't checked.

**Comment by amandeepmittal** [comment]
@QuincyLarson I am able to access it now. Thanks!

@spences10 I have made a new PR, let us try it with that one and see what happens.

**Pull request merged**
