### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by amandeepmittal**
Fixes # Doc

### Change proposed in this pull request:
  - update badges

  - added more features
 

---
###### Thanks to [@miljan-fsd] from [parcel-react-app] for the template 👌

[@miljan-fsd]: https://github.com/miljan-fsd
[parcel-react-app]: https://github.com/miljan-fsd/parcel-react-app

### CODE REVIEW

**Comment by spences10** [comment]
I notice the CI wasn't working because of snyk @amandeepmittal, for vulnerabilities I have been using the GitHub built in check which I have found to be as effective and removes the additional overhead needed with snyk

**Comment by amandeepmittal** [comment]
Are you suggesting that we use the built-in check and completely remove snyk?

**Comment by amandeepmittal** [comment]
No I have such desire like that 😆.

I  using Github's built in tool for auditing for my other projects. They are fine. Will update the repo and remove snyk as a patch shortly. 👍 Thanks for recommending this process.

**Comment by spences10** [comment]
And with regard to patches for the `patch` branch, we could consider Renovate which you can configure to apply patches (to the `patch` branch) and only request a review when there is a major version bump.

The only manual intervention will be merging `patch` into `develop` 

We could have a `renovate.json` that looks something like this:
 
```json
{
  "extends": ["config:base"],
  "reviewers": [
    "QuincyLarson ",
    "amandeepmittal",
    "spences10",
  ],
  "bumpVersion": "patch",
  "baseBranches": ["patch"],
  "automerge": true,
  "major": {
    "automerge": false
  }
}
```

**Pull request merged**
