### PR TITLE
Dev/spences10/move licence patch

### PR DESCRIPTION
**Pull request by spences10**
Move licence from `.github` community files folder to the root of the app where it should be (oops 🙃) updated the year on the Licence too

### CODE REVIEW

**Comment by amandeepmittal** [comment]
I will recommend that when you are making changes, do consider changing the version of the project in `package.json`. The reason being, such that, we then would not have to pull a new request just to update the `package.json` file.

**Comment by spences10** [comment]
Brill, something that should go into the docs I guess? I know that can be automated in a CI pipeline actually 😄

**Comment by amandeepmittal** [comment]
@spences10 yes! We should add this to our #131. 👌

**Comment by spences10** [comment]
I started looking at it yesterday but didn't actually make any changes 🙃 

Have you looked into the CI process anymore @amandeepmittal?

**Comment by amandeepmittal** [comment]
I did took a look into the link you shared for CI over the weekend. The problem or the confusion I am having right now is that the production and github code for bot are both separate. Remember the access I gave you for the heroku deployment? It had a different name. 

I am trying to find could we have a single travis CI for both of them or somehow use this github repo with heroku directly?

**Comment by spences10** [comment]
Yeah, Heroku has its own fork of the code IIRC, I haven't used Heroku for some time to be fair though. I always found using Zeit now to be a lot less of a config overhead 😁

**Comment by amandeepmittal** [comment]
Will keep you update on the matter.

**Pull request merged**
